stages:
  - test
  - build
  - bundle

test:
  image: leapcode/soledad:latest
  stage: test
  script:
    - tox --recreate -e py27-dev

build:
  image: leapcode/bitmask-dev:latest
  stage: build
  script:
    - virtualenv venv
    - source venv/bin/activate
    - make dev-backend
    - mkdir -p /root/.config/leap/
    - bitmaskd
    - bitmaskctl status

bundle:
  image: leapcode/bitmask-dev:latest
  stage: bundle 
  script: pkg/build_bundle_with_venv.sh
  artifacts:
    paths:
      - dist/*.tar.gz
